// spot@public.aggre.bookTicker.v3.api.pb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: PublicAggreBookTickerV3Api.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicAggreBookTickerV3Api struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BidPrice    string `protobuf:"bytes,1,opt,name=bidPrice,proto3" json:"bidPrice,omitempty"`
	BidQuantity string `protobuf:"bytes,2,opt,name=bidQuantity,proto3" json:"bidQuantity,omitempty"`
	AskPrice    string `protobuf:"bytes,3,opt,name=askPrice,proto3" json:"askPrice,omitempty"`
	AskQuantity string `protobuf:"bytes,4,opt,name=askQuantity,proto3" json:"askQuantity,omitempty"`
}

func (x *PublicAggreBookTickerV3Api) Reset() {
	*x = PublicAggreBookTickerV3Api{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PublicAggreBookTickerV3Api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicAggreBookTickerV3Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicAggreBookTickerV3Api) ProtoMessage() {}

func (x *PublicAggreBookTickerV3Api) ProtoReflect() protoreflect.Message {
	mi := &file_PublicAggreBookTickerV3Api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicAggreBookTickerV3Api.ProtoReflect.Descriptor instead.
func (*PublicAggreBookTickerV3Api) Descriptor() ([]byte, []int) {
	return file_PublicAggreBookTickerV3Api_proto_rawDescGZIP(), []int{0}
}

func (x *PublicAggreBookTickerV3Api) GetBidPrice() string {
	if x != nil {
		return x.BidPrice
	}
	return ""
}

func (x *PublicAggreBookTickerV3Api) GetBidQuantity() string {
	if x != nil {
		return x.BidQuantity
	}
	return ""
}

func (x *PublicAggreBookTickerV3Api) GetAskPrice() string {
	if x != nil {
		return x.AskPrice
	}
	return ""
}

func (x *PublicAggreBookTickerV3Api) GetAskQuantity() string {
	if x != nil {
		return x.AskQuantity
	}
	return ""
}

var File_PublicAggreBookTickerV3Api_proto protoreflect.FileDescriptor

var file_PublicAggreBookTickerV3Api_proto_rawDesc = []byte{
	0x0a, 0x20, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x41, 0x67, 0x67, 0x72, 0x65, 0x42, 0x6f, 0x6f,
	0x6b, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x56, 0x33, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x98, 0x01, 0x0a, 0x1a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x41, 0x67, 0x67,
	0x72, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x56, 0x33, 0x41, 0x70,
	0x69, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x69, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x62, 0x69, 0x64, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x62, 0x69, 0x64, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61,
	0x73, 0x6b, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x52, 0x0a,
	0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x78, 0x63, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x1f, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x41, 0x67, 0x67, 0x72, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x72, 0x56, 0x33, 0x41, 0x70, 0x69, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x01,
	0x50, 0x01, 0x5a, 0x0d, 0x77, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x64, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PublicAggreBookTickerV3Api_proto_rawDescOnce sync.Once
	file_PublicAggreBookTickerV3Api_proto_rawDescData = file_PublicAggreBookTickerV3Api_proto_rawDesc
)

func file_PublicAggreBookTickerV3Api_proto_rawDescGZIP() []byte {
	file_PublicAggreBookTickerV3Api_proto_rawDescOnce.Do(func() {
		file_PublicAggreBookTickerV3Api_proto_rawDescData = protoimpl.X.CompressGZIP(file_PublicAggreBookTickerV3Api_proto_rawDescData)
	})
	return file_PublicAggreBookTickerV3Api_proto_rawDescData
}

var file_PublicAggreBookTickerV3Api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PublicAggreBookTickerV3Api_proto_goTypes = []interface{}{
	(*PublicAggreBookTickerV3Api)(nil), // 0: PublicAggreBookTickerV3Api
}
var file_PublicAggreBookTickerV3Api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PublicAggreBookTickerV3Api_proto_init() }
func file_PublicAggreBookTickerV3Api_proto_init() {
	if File_PublicAggreBookTickerV3Api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PublicAggreBookTickerV3Api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicAggreBookTickerV3Api); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PublicAggreBookTickerV3Api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PublicAggreBookTickerV3Api_proto_goTypes,
		DependencyIndexes: file_PublicAggreBookTickerV3Api_proto_depIdxs,
		MessageInfos:      file_PublicAggreBookTickerV3Api_proto_msgTypes,
	}.Build()
	File_PublicAggreBookTickerV3Api_proto = out.File
	file_PublicAggreBookTickerV3Api_proto_rawDesc = nil
	file_PublicAggreBookTickerV3Api_proto_goTypes = nil
	file_PublicAggreBookTickerV3Api_proto_depIdxs = nil
}
